spring.application.name=void-terminal-agent
spring.main.web-application-type=none
voidterminal.agent.node-id=
voidterminal.agent.node-name=
voidterminal.agent.server-url=http://localhost:8080
voidterminal.agent.report-interval=1s
voidterminal.agent.ping.unicom=ha-cu-v4.ip.zstaticcdn.com
voidterminal.agent.ping.mobile=ha-cm-v4.ip.zstaticcdn.com
voidterminal.agent.ping.telecom=222.88.88.88
